### ISSUE TITLE
mac osx10.11 sublime3build3083 安装后没有弹窗

### ISSUE THREAD

**Issue by yekz** [yangweijie/SublimePHPNinJaManual#1]
只有状态栏显示了下 Finding done.

**Comment by yangweijie** [comment]
你先确保命令行里 php -v 可用。 然后按照 看 Sublime的终端， 看有什么报错，注意事项里 有个因为语言配置导致查询失败的错误。有其他错误可以qq wiebo 向我反应

**Comment by yekz** [comment]
php -v

```
PHP 5.6.13 (cli) (built: Sep 21 2015 19:26:57)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

确认已复制创建 user setting

``` json
{
    "lang":"zh"
}
```

console：

```
Exception in thread Thread-243:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/kezhong/Library/Application Support/Sublime Text 3/Packages/PhpNinJaManual/PhpNinJaManual.py", line 50, in run
    path = packages_path + os.sep + 'php_docs' + os.sep + lang + os.sep
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by yangweijie** [comment]
多保存语言配置文件，知道终端里看到zh ，然后拿 json_encode 函数测试

**Comment by NewdawnALM** [comment]
您好，我使用package control安装后右键点击“查看函数说明”时在sublime的控制台总是出现
zh
php "/home/newdawn/.config/sublime-text-3/Packages/PhpNinJaManual/index.php" "Doc/find/function/sublime/lang/zh"
Exception in thread Thread-532:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/home/newdawn/.config/sublime-text-3/Packages/PhpNinJaManual/PhpNinJaManual.py", line 57, in run
    html = self.get_comment(self.word, lang)
  File "/home/newdawn/.config/sublime-text-3/Packages/PhpNinJaManual/PhpNinJaManual.py", line 69, in get_comment
    tmp = sublime.decode_value(data).replace('\\n', '<br>')
  File "/opt/sublime_text/sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Expected value in (data):1:1
这个错误，请问是我的环境的问题吗？该怎么样解决呢？
