### ISSUE TITLE
报告一个BUG，咸鱼看不太懂

### ISSUE THREAD

**Issue by ghost** [yangweijie/SublimePHPNinJaManual#4]
php "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\index.php" "Doc/find/function/mkdir/lang/zh"
Exception in thread Thread-907:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\PhpNinJaManual.py", line 57, in run
    html = self.get_comment(self.word, lang)
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\PhpNinJaManual.py", line 69, in get_comment
    tmp = sublime.decode_value(data).replace('\\n', '<br>')
  File "D:\Program Files\Sublime Text 3\sublime.py", line 215, in decode_value
    raise ValueError(err)
ValueError: Error trying to decode value: Expected value in (data):1:1

**Comment by ghost** [comment]
could not find driver
FILE: C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Db\Driver.class.php(109)
#0 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Db\Driver.class.php(109): E('could not find ...')
#1 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Db\Driver.class.php(1066): Think\Db\Driver->connect()
#2 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Db\Driver.class.php(140): Think\Db\Driver->initConnect(false)
#3 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Db\Driver\Sqlite.class.php(38): Think\Db\Driver->query('PRAGMA table_in...')
#4 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Model.class.php(134): Think\Db\Driver\Sqlite->getFields('funlist')
#5 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Model.class.php(122): Think\Model->flush()
#6 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Model.class.php(1434): Think\Model->_checkTableInfo()
#7 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Model.class.php(97): Think\Model->db(0, '', true)
#8 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Common\functions.php(621): Think\Model->__construct('funlist', '', '')
#9 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\App\Home\Controller\DocController.class.php(56): M('funlist')
#10 [internal function]: Home\Controller\DocController->find('mkdir', 'zh')
#11 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\App.class.php(162): ReflectionMethod->invokeArgs(Object(Home\Controller\DocController), Array)
#12 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\App.class.php(202): Think\App::exec()
#13 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\Library\Think\Think.class.php(120): Think\App::run()
#14 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\ThinkPHP\ThinkPHP.php(97): Think\Think::start()
#15 C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\index.php(24): require('C:\\Users\\admin\\...')
#16 {main}

把data打出来是这样。TP的东西不懂啊。

**Comment by ghost** [comment]
啊，好像得装上PHP的sqlite扩展，装上后又换了一个报错
Styled Popup: Parsing color scheme
Exception in thread Thread-1936:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\PhpNinJaManual.py", line 57, in run
    html = self.get_comment(self.word, lang)
  File "C:\Users\admin\AppData\Roaming\Sublime Text 3\Packages\PhpNinJaManual\PhpNinJaManual.py", line 71, in get_comment
    styled_popup.show_popup(self.view, tmp, on_navigate=self.nav, max_width=700)
  File "C:\Users\admin\AppData\Roaming\SUBLIM~1\Packages\STYLED~1\st3\styled_popup.py", line 20, in show_popup
    style_sheet = manager.get_stylesheet(color_scheme)["content"]
  File "C:\Users\admin\AppData\Roaming\SUBLIM~1\Packages\STYLED~1\st3\styled_popup.py", line 107, in get_stylesheet
    scheme_css = SchemeParser().run(color_scheme)
  File "C:\Users\admin\AppData\Roaming\SUBLIM~1\Packages\STYLED~1\st3\styled_popup.py", line 159, in run
    scheme = self.read_scheme(content)
  File "C:\Users\admin\AppData\Roaming\SUBLIM~1\Packages\STYLED~1\st3\styled_popup.py", line 173, in read_scheme
    return  readPlistFromBytes(scheme)
  File "./python3.3/plistlib.py", line 104, in readPlistFromBytes
  File "./python3.3/plistlib.py", line 76, in readPlist
  File "./python3.3/plistlib.py", line 378, in parse
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by ghost** [comment]
好像是主题的问题，打印了一下我的主题
print(self.view.settings().get("color_scheme"))
Packages/Theme - Monokai Pro/Monokai Classic.sublime-color-scheme
换了个主题就正常了
Packages/Material Theme/schemes/Material-Theme-Lighter.tmTheme

**Comment by ghost** [comment]
啊，还是有问题，我把包管理下载的删了，从GIT拉了一份
把这里的PHP路径改一下，PhpBox.sublime-settings，注意使用的PHP版本得大于7.2，然后开启curl和sqlite模块，不然会报错..

**Comment by yangweijie** [comment]
嗯 上面 报的是xml 无法正常解析吧
